[package]
name = "kdf-argon2id"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
argon2 = "0.5"
rand = "0.8"
hex = "0.4"
rpassword = "7.3"
base64 = "0.22"
